### PR TITLE
Add startAdvertise method for eddystone

### PR DESCRIPTION
**Pull request by adam-h**
This adds the ability to start advertising a eddystone beacon (on android devices that support it)

### CODE REVIEW

**Comment by mikaelkindborg** [comment]
@adam-h Many thanks for this contribution, will look into merging your code. This is great to have!

**Comment by mikaelkindborg** [comment]
@adam-h Sorry for the delay, will attend this now.

**Comment by mikaelkindborg** [comment]
@adam-h Hi again, tested the code, fixed some issues. Great if you can have a look.

Replaced Uint8Array.from(data) with new Uint8Array.(data) since the .from function is not commonly supported on mobile.

Also updated how isAdvertising is set.

See this commit for details: https://github.com/evothings/evothings-libraries/commit/70791a97805e6667504a9a0edda516b5fc9ec972

Also updated easyble.js and built generated files, see the commit log: https://github.com/evothings/evothings-libraries/commits/master

Made a test app that I used to test advertising as Eddystone: https://github.com/evothings/evothings-demos/tree/master/eddystone-beacon

Your code works great! Many thanks for the contribution!

**Comment by adam-h** [comment]
👍 Thanks! Nice improvements :)

**Pull request merged**
