### PR TITLE
Write to characteristic without response (easyble), update dialog-iotsensor library, change order of parameters in startScan (easyble)

### PR DESCRIPTION
**Pull request by nbezembinder1**
See comment from [commit](https://github.com/nbezembinder1/evothings-libraries/commit/89e4fc8f275f94d252e086d969b9d5d00a2af9d8).

### CODE REVIEW

**Comment by nbezembinder1** [comment]
The functions `writeCharacteristic` and `writeServiceCharacteristic` no longer work on Android when using the Evothings Viewer version 1.4 (Version 1.3 works fine) when the characteristic attribute is set to `WRITE WITHOUT RESPONSE`. When using Evothings Viewer 1.4 error code `0x06: Attribute server does not support the request received from the client.` is returned.

**Comment by mikaelkindborg** [comment]
@nbezembinder1 Hi Nick, sorry for the long delay in attending your pull request.

I am curious about this commit: "Change order of parameters in startScan function" https://github.com/evothings/evothings-libraries/pull/8/commits/a0edc90e2a5a9ad6eeab54037010aac739e64b42

Why do you want serviceUUIDs to be last parameter? Is that better/more logical than putting it first?

**Comment by nbezembinder1** [comment]
@mikaelkindborg I believe this is related to our Dialog IoT Sensor library. The `serviceUUIDs` were added later to the `easyble` library. When using our library with the `easyble` library this caused some issues. 

Also, putting the `serviceUUIDs` as the last parameter seemed more logical as this is an optional parameter.

I do understand that changing the order of parameters can cause some issues in the future for other users.

**Comment by mikaelkindborg** [comment]
@nbezembinder1 Thanks a lot for the explanation! I could move it last and still keep the check for having it first for backwards compatibility.

**Pull request merged**
